# Generated by Django 4.2.11 on 2026-04-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_dob_user_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_student',
            field=models.BooleanField(default=True),
        ),
    ]
