# Generated by Django 4.2.11 on 2026-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_active_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='student_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(default='Trainer', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='trainer/documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_trainer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trainer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainer/photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='trainer_reg_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
