# Generated by Django 4.2.11 on 2026-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_photo_user_student_photo_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trainer_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
