# Generated by Django 4.2.11 on 2026-04-13 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_section'),
        ('accounts', '0006_alter_user_trainer_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainers', to='schools.school'),
        ),
    ]
