# Generated by Django 4.2.11 on 2026-04-18 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0006_rename_allow_attendance_edit_school_attendance_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('class_name', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_hour', models.IntegerField(default=0)),
                ('full_marks', models.IntegerField(default=100)),
                ('pass_marks', models.IntegerField(default=40)),
                ('theory_marks', models.IntegerField(default=70)),
                ('internal_marks', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('hidden', 'Hidden')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='schools.school')),
            ],
            options={
                'unique_together': {('course', 'school')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='schools',
            field=models.ManyToManyField(related_name='courses', through='courses.CourseAssignment', to='schools.school'),
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
