# Generated by Django 4.2.11 on 2026-04-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='internal_obtained',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='theory_obtained',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
