# Generated by Django 4.2.11 on 2026-04-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
