# Generated by Django 4.2.11 on 2026-04-18 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_rename_allow_attendance_edit_school_attendance_locked_and_more'),
        ('courses', '0002_courseregistration_internal_obtained_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_examregistration_delete_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examregistration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='examregistration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='remarks',
            field=models.CharField(blank=True, help_text='Student should enter Name - RegNo - School', max_length=255),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='examregistration',
            unique_together={('student', 'course')},
        ),
    ]
