# Generated by Django 4.2.11 on 2026-04-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='allow_attendance_edit',
            field=models.BooleanField(default=False),
        ),
    ]
