# Generated by Django 4.2.11 on 2026-04-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_allow_attendance_edit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='allow_attendance_edit',
            new_name='attendance_locked',
        ),
        migrations.AddField(
            model_name='school',
            name='attendance_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='school_can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='trainer_can_edit',
            field=models.BooleanField(default=False),
        ),
    ]
