# Generated by Django 6.0.4 on 2026-04-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_remove_topic_description_remove_topic_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus/files/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='syllabus/images/'),
        ),
    ]
