# Generated by Django 4.2.11 on 2026-04-21 08:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_topic_description_topic_file_topic_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['class_name']},
        ),
        migrations.AddField(
            model_name='syllabus',
            name='allow_for_trainee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
