# Generated by Django 4.2.11 on 2026-04-21 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('syllabus', '0006_alter_syllabus_options_syllabus_allow_for_trainee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='allow_edit_for_trainee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='allow_for_view',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
