# Generated by Django 4.2.11 on 2026-04-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_syllabus_allow_edit_for_trainee_topic_allow_for_view_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='allow_for_view',
            field=models.BooleanField(default=True),
        ),
    ]
