# Generated by Django 4.2.11 on 2026-04-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_rename_allow_attendance_edit_school_attendance_locked_and_more'),
        ('syllabus', '0008_phase_allow_for_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='schools.school'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('school', 'class_name')},
        ),
    ]
